FROM mcr.microsoft.com/devcontainers/base:ubuntu

RUN apt-get update &&/ 
    apt-get install -y xz-utils

# install python 3.11 and pip and run pip install Flask flask-cors pdfminer.six chardet PyMuPDF

# install nodejs and npm and run npm install